### ISSUE TITLE
Problem in Detection on Customized Data

### ISSUE THREAD

**Issue by mfaramarzi** [CVxTz/medical_image_segmentation#11]
Hello Mansar @CVxTz 

I am trying to predict on my customized images. 
As a transfer learning step, learnt weights of retinal-vessels image segmentation model was used as the initial weight to train a model to segment cracks on the pavement.
However since model could not distinguish between edges (e.g. shadows, cars, traffic signs etc) in the images, it then was fine tuned (retinal weights as initial weights) by training on 58 road images ( mostly images with misleading  features such as shadows, vehicles, branches, traffic signs etc) correctly labeled . However as you can see below in fig "d", tested road images does not show a good result. 
Do you have any idea what is the reason of that?
![image](https://user-images.githubusercontent.com/44882423/100655173-ec341500-3318-11eb-9a28-ac2830d60e8f.png)
Here you can also see directory tree of my model.
[output.txt.](https://github.com/CVxTz/medical_image_segmentation/files/5618339/output.txt)

**Comment by CVxTz** [comment]
The cracks are barely visible and the image quality is bad. You probably need more data of higher quality. But I can't say for sure with just two samples.

Best of luck,

Youness

**Comment by mfaramarzi** [comment]
> . But I can't say for sure with just two samples.

These images are actually 4 steps of processing one sample. I doubt if it could be related to the resolution of image. As you can see fig **3.d** is kindda all gray, while it was expected to be similar to fig 3.c.

**Comment by CVxTz** [comment]
Yea its probably because your model has a hard time coverging when initialized randomly, its why I said you need more data.
How many samples do you have ?
