### ISSUE TITLE
Adjusting High Sensitivity in Predicted Retinal

### ISSUE THREAD

**Issue by mfaramarzi** [CVxTz/medical_image_segmentation#13]
Helllo Youness @CVxTz 

As you can see below (left: baseline, center: aug, right, aug_vgg) the detection result of mine seems different than your. Is there anyway to reduce sensitivity (any hypermarket to adjust?) and to achieve result like yours? Thank you

![unnamed](https://user-images.githubusercontent.com/44882423/101651024-98a58380-3a0a-11eb-990b-42b798c728d5.jpg)

![image](https://user-images.githubusercontent.com/44882423/101651129-b672e880-3a0a-11eb-84ec-16a398d5e456.png)

**Comment by CVxTz** [comment]
This is very odd :/ Maybe you should train the network longer ? 
Another option is to threshold your predictions at something like 0.7 before saving them as images.
Sorry for not being more helpful, its been a while since I worked on this.

**Comment by mfaramarzi** [comment]
> This is very odd :/ Maybe you should train the network longer ?
> Another option is to threshold your predictions at something like 0.7 before saving them as images.
> Sorry for not being more helpful, its been a while since I worked on this.

Hello Youness,
I trained with 200 epochs and the tested, the prediction was as below:

![IMG-2499](https://user-images.githubusercontent.com/44882423/101791648-c73a6180-3ad1-11eb-878a-4352759fe25f.jpg)

Then I tested with threshold = 0.7 (100 epochs) assuming that the following lines are in charge with the threshold:
for p in range(pred_.shape[0]):
                for q in range(pred_.shape[1]):
                    if mask_[p,q]>0.7: # Inside the mask pixels only
                        gt_flat.append(gt_[p,q])
                        pred_flat.append(pred_[p,q])
and I got the prediction result as below:

![IMG-2501](https://user-images.githubusercontent.com/44882423/101791661-ca355200-3ad1-11eb-8b93-206f900a54d7.jpg)

1. Any comment would be appreciated.
2. Also are the above lines in charge for threshold?

P.S. In both scenarios AUC ROC ~  0.975

**Comment by CVxTz** [comment]
Hello
You need to threshold **pred_** and not mask

**Comment by mfaramarzi** [comment]
> threshold **pred_**

Which line is in charge of threshold pred_?
I tried manipulating the following line (if that is the line) and still no improvement.
`gt_ = (seg[i]>0.7).astype(int)`
