### ISSUE TITLE
Plot code

### ISSUE THREAD

**Issue by aficionadoai** [CVxTz/medical_image_segmentation#14]
Do you have the code for these plots [Prediction results](https://camo.githubusercontent.com/718872051124b650d10a35243320843870e439cab536a63b047063c6c36d6416/68747470733a2f2f63646e2d696d616765732d312e6d656469756d2e636f6d2f6d61782f323536302f312a63776b75744e6d7647723747332d4b504e44534763672e706e67)

**Comment by CVxTz** [comment]
Its in the repo : https://github.com/CVxTz/medical_image_segmentation/blob/master/code/plot_differences.py

**Comment by aficionadoai** [comment]
Does this code produce this image 
![image](https://user-images.githubusercontent.com/61476831/104093562-d4717a00-5250-11eb-8aeb-826e75f4058c.png)
