### ISSUE TITLE
problems with validation test

### ISSUE THREAD

**Issue by smoreschini** [CVxTz/medical_image_segmentation#2]
Hi, Sorry to bother, I'm trying to run the experiment and I noticed that when calling the validation set you are expecting a folder known as "2nd_manual". I downloaded the dataset from the DRIVE datasets but such folder is missing.

**Comment by CVxTz** [comment]
Hello,

It was there when I downloaded the dataset at the time. I cannot host the
dataset on my repository as I don't own the data.
You can always change the paths if needed, just be careful to not mix train
and test.

Best,

Youness

Le mer. 4 mars 2020 à 10:56, moreschini16 <notifications@github.com> a
écrit :

**Comment by mfaramarzi** [comment]
> Hi, Sorry to bother, I'm trying to run the experiment and I noticed that when calling the validation set you are expecting a folder known as "2nd_manual". I downloaded the dataset from the DRIVE datasets but such folder is missing.

You can find it from other GitHub repositories. Google it if you have not yet.
