### ISSUE TITLE
Error: unable to open file

### ISSUE THREAD

**Issue by mfaramarzi** [CVxTz/medical_image_segmentation#5]
@CVxTz 

Hello Younes,
Thank you for sharing your job. When I run run.sh I following error pops up. Can you help me with that please?
Tnx in advance

`OSError: Unable to open file (unable to open file: name = 'baseline_unet_do_0.1_activation_ReLU_weights.best.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

**Comment by CVxTz** [comment]
Does it stop the training ? bc its between a try-catch clause : 

    try:
        model.load_weights(file_path, by_name=True)
    except:
        pass
I did that because I want to resume training if the model files already exist.

**Comment by mfaramarzi** [comment]
@CVxTz 
Yes it seems to start training but stops at the first epoch.  Logs_baseline files are being made at "code" folder and folders are made at "output" as you can see below:

![image](https://user-images.githubusercontent.com/44882423/84502211-eae93000-ac85-11ea-84fd-724f22e75a74.png)



![image](https://user-images.githubusercontent.com/44882423/84502346-28e65400-ac86-11ea-89c5-f7b803c68002.png)

**Comment by CVxTz** [comment]
Does your python process have the rigths to write on the disk ?

**Comment by mfaramarzi** [comment]
> 
> 
> Does your python process have the rigths to write on the disk ?

I believe so, it's my personal PC and I have written on the disk before.

**Comment by mfaramarzi** [comment]
@CVxTz 
why is it trying to open `h5py/_objects.pyx` while there is not such a folder as `h5py`?

![Screenshot from 2020-06-28 09-00-41](https://user-images.githubusercontent.com/44882423/85948302-2cccd400-b91e-11ea-9091-ea6123c0cc05.png)

**Comment by mfaramarzi** [comment]
Update, I could fix this problem by running Python files one by one and fixing errors with respect to each of them, instead of running all together in run.sh
