### ISSUE TITLE
ValueError: y has 0 samples: []

### ISSUE THREAD

**Issue by mfaramarzi** [CVxTz/medical_image_segmentation#6]
@CVxTz 
Hello Mansar,

I have entered the image, mask and 2nd_manual addresses in three prediction Python files, according to their address on my machine, but getting the following error when running predictions. Do you have any idea why it's happening?
Thanx in advance.

![image](https://user-images.githubusercontent.com/44882423/86403847-831e7780-bc7c-11ea-9e86-ca2b43f04ae8.png)

**Comment by CVxTz** [comment]
Hey,

Maybe you did not specify the path correctly, can you print the list of images to see if its not empty ?

Best,

Youness

**Comment by mfaramarzi** [comment]
@CVxTz 

Update: Reason of this problem was using a different format of images (.png) in the 2nd_manual folder instead of ".gif" format.
Happened due to downloading that folder's contents from a different source. Anyway, Tnx Youness!
