### ISSUE TITLE
Three .py files

### ISSUE THREAD

**Issue by mfaramarzi** [CVxTz/medical_image_segmentation#7]
@CVxTz 

Hello Youness,
What is the difference between the function of three below ".py" files:

- baseline_aug_vgg.py
- baseline.py
- baseline_aug.py

The same question is true for their corresponding prediction files. Thanks!

**Comment by CVxTz** [comment]
Hey,

its been a while but if my memory is correct then baseline.py is the baseline model, baseline_aug.py uses data augmentation during training and baseline_aug_vgg.py uses data augmentation and pretrained vgg architecture.
