### ISSUE TITLE
Prediction on Custom Dataset

### ISSUE THREAD

**Issue by mfaramarzi** [CVxTz/medical_image_segmentation#8]
@CVxTz 

Hello Youness,
How can I run a prediction on raw .jpg custom datasets? Thanks in advance.

**Comment by CVxTz** [comment]
you can change the prediction .py files so it looks for jpg images here : 

    val_data = list(zip(sorted(glob('../input/DRIVE/test/images/*.**tif**')), => here change the extention
                          sorted(glob('../input/DRIVE/test/2nd_manual/*.**gif**')),
                        sorted(glob('../input/DRIVE/test/mask/*.**gif**'))))


If you dont have the ground truth you might have to change other parts of the code.
