### ISSUE TITLE
Problem in Running the trained model in Windows

### ISSUE THREAD

**Issue by hmhtb** [CVxTz/medical_image_segmentation#9]
Hi,
I trained my model in the linux and now I'm trying to run the prediction using the pretrained model in Windows. However, I get the error "dtype=float32)> has shape (3, 3, 32, 32), but the saved weight has shape (32, 3, 3, 3)." 

Any thought on that?

**Comment by CVxTz** [comment]
I dont do windows, sorry. It is a bad OS for python developement.
